# Generated by Django 2.1.1 on 2018-09-15 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ideabox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(db_column='TYPE', max_length=50)),
            ],
            options={
                'db_table': 'IDEABOX',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IdeaNeeds',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('requirement', models.CharField(db_column='REQUIREMENT', max_length=100)),
                ('description', models.CharField(blank=True, db_column='DESCRIPTION', max_length=200, null=True)),
                ('idea_box', models.CharField(db_column='IDEA_BOX', max_length=200)),
            ],
            options={
                'db_table': 'IDEA_NEEDS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ideas',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('idea_title', models.CharField(db_column='IDEA_TITLE', max_length=100)),
                ('idea_description', models.CharField(db_column='IDEA_DESCRIPTION', max_length=500)),
                ('idea_owner', models.CharField(db_column='IDEA_OWNER', max_length=50)),
                ('reviewer_name', models.CharField(db_column='REVIEWER_NAME', max_length=50)),
                ('tags', models.CharField(db_column='TAGS', max_length=50)),
                ('submission_date', models.DateTimeField(db_column='SUBMISSION_DATE')),
                ('update_date', models.DateTimeField(db_column='UPDATE_DATE')),
                ('review_status', models.CharField(db_column='REVIEW_STATUS', max_length=20)),
                ('review_comment', models.CharField(blank=True, db_column='REVIEW_COMMENT', max_length=200, null=True)),
                ('category', models.CharField(db_column='CATEGORY', max_length=50)),
                ('submitted_against', models.IntegerField(db_column='SUBMITTED_AGAINST')),
            ],
            options={
                'db_table': 'IDEAS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InnovationManagers',
            fields=[
                ('manager_id', models.AutoField(db_column='MANAGER_ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='NAME', max_length=50)),
                ('email', models.CharField(db_column='EMAIL', max_length=50)),
                ('request_count', models.IntegerField(db_column='REQUEST_COUNT')),
            ],
            options={
                'db_table': 'INNOVATION_MANAGERS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reviewers',
            fields=[
                ('reviewer_id', models.AutoField(db_column='REVIEWER_ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='NAME', max_length=50)),
                ('email', models.CharField(db_column='EMAIL', max_length=50)),
                ('experties', models.CharField(db_column='EXPERTIES', max_length=50)),
                ('number_of_reviews', models.IntegerField(db_column='NUMBER_OF_REVIEWS')),
            ],
            options={
                'db_table': 'REVIEWERS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReviewStatus',
            fields=[
                ('status', models.CharField(db_column='STATUS', max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'REVIEW_STATUS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('role', models.CharField(db_column='ROLE', max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'ROLES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_column='TAG', max_length=30, unique=True)),
            ],
            options={
                'db_table': 'TAGS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.BigAutoField(db_column='USER_ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='NAME', max_length=50)),
                ('role', models.CharField(db_column='ROLE', max_length=50)),
                ('email', models.CharField(db_column='EMAIL', max_length=50, unique=True)),
            ],
            options={
                'db_table': 'USERS',
                'managed': False,
            },
        ),
    ]
