# Generated by Django 2.1.3 on 2019-02-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DAO_API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Auth',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BoxOwner',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('innovation_manager_name', models.CharField(db_column='INNOVATION_MANAGER_NAME', max_length=100)),
                ('idea_box', models.CharField(db_column='IDEA_BOX', max_length=50)),
            ],
            options={
                'db_table': 'BOX_OWNER',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('idea_id', models.BigIntegerField(db_column='IDEA_ID')),
                ('decision', models.CharField(db_column='DECISION', max_length=50)),
                ('comment', models.CharField(blank=True, db_column='COMMENT', max_length=200, null=True)),
                ('need_id', models.BigIntegerField(db_column='NEED_ID')),
            ],
            options={
                'db_table': 'DECISION',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DecisionStatus',
            fields=[
                ('value', models.CharField(db_column='VALUE', max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'DECISION_STATUS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReviewerIdeaMapping',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reviewer', models.CharField(db_column='REVIEWER', max_length=100)),
                ('idea_id', models.BigIntegerField(db_column='IDEA_ID')),
                ('review_comment', models.CharField(blank=True, db_column='REVIEW_COMMENT', max_length=200, null=True)),
                ('review_status', models.CharField(blank=True, db_column='REVIEW_STATUS', max_length=20, null=True)),
                ('review_date', models.DateTimeField(blank=True, db_column='REVIEW_DATE', null=True)),
            ],
            options={
                'db_table': 'REVIEWER_IDEA_MAPPING',
                'managed': False,
            },
        ),
    ]
