service: library
runtime: nodejs8
instance_class: F2
automatic_scaling:
  target_throughput_utilization: 0.6
  min_instances: 2
  max_instances: 10
  max_concurrent_requests: 10
  min_pending_latency: 30ms
  max_pending_latency: automatic
