apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: changeme
    context: .
    docker: {}
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/shreya1396/gcppoc:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
profiles:
- name: dev
  build:
    artifacts:
    - docker: {}
    tagPolicy:
      envTemplate:
        template: '{{.DOCKER_REGISTRY}}/shreya1396/gcppoc:{{.DIGEST_HEX}}'
    local: {}
  deploy:
    helm:
      releases:
      - name: gcppoc
        chartPath: charts/gcppoc
        setValueTemplates:
          image.repository: '{{.DOCKER_REGISTRY}}/shreya1396/gcppoc'
          image.tag: '{{.DIGEST_HEX}}'
